version: '2'
services:
  web:
    build: .
    ports:
      - '8080:8080'
      - '5005:5005'
    depends_on:
      - db
    volumes:
      - 'static-data:/var/static/'
  db:
    image: 'postgres:11.5'
    ports:
      - '5432:5432'
    volumes:
      - 'db-data:/var/lib/postgresql/data'

volumes:
  db-data:
  static-data:
