version: '2'
services:
  web:
    build: .
    ports:
      - '8080:8080'
      - '5005:5005'
    depends_on:
      - db
      - es
    volumes:
      - 'static-data:/var/static/'
  db:
    image: 'postgres:11.5'
    ports:
      - '5432:5432'
    volumes:
      - 'db-data:/var/lib/postgresql/data'
  es:
    image: 'docker.elastic.co/elasticsearch/elasticsearch:7.4.0'
    ports:
      - '9200:9200'
      - '9300:9300'
    environment:
      - 'discovery.type=single-node'
      - 'node.name=es'

volumes:
  db-data:
  static-data:
