version: '2'
services:
  web:
    build: .
    ports:
      - '8080:8080'
      - '5005:5005'
    depends_on:
      - db
      - ts
    volumes:
      - 'static-data:/var/static/'
  db:
    image: 'postgres'
    ports:
      - '5432:5432'
    volumes:
      - 'db-data:/var/lib/postgresql/data'
  ts:
    image: 'typesense/typesense:0.11.0'
    ports:
      - '8108:8108'
    volumes:
      - 'ts-data:/data'
    command:
      --data-dir /data --api-key=Hu52dwsas2AdxdE

volumes:
  db-data:
  static-data:
  ts-data:
